"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../assets/styles/globals.css";
import { Toaster } from "react-hot-toast";
import { RecoilRoot } from "recoil";
// import { CacheProvider, EmotionCache } from "@emotion/react";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RecoilRoot>
          <Toaster position="top-right" reverseOrder={false} />
          {children}
        </RecoilRoot>
      </body>
    </html>
  );
}
